# Generated by Django 3.1.5 on 2021-02-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0002_contactinfo1_student1_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd1', models.CharField(max_length=64)),
                ('fd2', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='m_app.parent')),
                ('fd3', models.CharField(max_length=64)),
                ('fd4', models.CharField(max_length=64)),
            ],
            bases=('m_app.parent',),
        ),
        migrations.CreateModel(
            name='Subchild',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='m_app.child')),
                ('fd5', models.CharField(max_length=64)),
            ],
            bases=('m_app.child',),
        ),
    ]
