# Generated by Django 2.2.3 on 2020-12-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201225_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eno', models.IntegerField()),
                ('esalary', models.FloatField()),
                ('eadd', models.CharField(max_length=50)),
            ],
        ),
    ]
